### PR TITLE
LIbretro updates

### PR DESCRIPTION
**Pull request by twinaphex**

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
What's the reason to don't merge it?

**Comment by OV2** [comment]
Mostly because I wanted to see if there is a better way to get the memory mapping export without sprinkling memmap.cpp with libretro defines, and I have not yet had the time to do so. I know it has almost been a year, I hope to get back to a more regular schedule soon.

**Comment by sergiobenrocha2** [comment]
There's an open bug about packaging in debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=643595

I think I'll own that ITP, I only need the libretro up-to-date and a new tag/release (last one was 4 years ago...).

It could be nice to see Snes9x on debian/ubuntu repos [again].

**Comment by OV2** [comment]
I'm not sure how an updated libretro part would help the debian package. If you want to package libretro only then it would be more of a retroarch support package.

**Comment by sergiobenrocha2** [comment]
You need to use the same source to package both, gtk and libretro. It's the debian policy. So I can choose package only snes9x-gtk, or only libretro core, or both in the same time and same source.

**Comment by sergiobenrocha2** [comment]
Just one note: seems this merge will brake netplay:

```
CXX      ../snes9x_gtk-netplay.o
../netplay.cpp:304:28: warning: missing terminating " character
             S9xNPSetError ("Unable to look up server's IP address from hostname.\n\n\"
                            ^
../netplay.cpp:304:13: error: missing terminating " character
             S9xNPSetError ("Unable to look up server's IP address from hostname.\n\n\"
             ^
../netplay.cpp:305:28: warning: missing terminating " character
                            "Unknown hostname or may be your nameserver isn't set\n\"
                            ^
../netplay.cpp:305:28: error: missing terminating " character
../netplay.cpp:339:28: warning: missing terminating " character
             S9xNPSetError ("Connection to remote server socket refused:\n\n\"
                            ^
../netplay.cpp:339:13: error: missing terminating " character
             S9xNPSetError ("Connection to remote server socket refused:\n\n\"
             ^
../netplay.cpp:340:28: warning: missing terminating " character
                            "Is there actually a Snes9X NetPlay server running\n\"
                            ^
../netplay.cpp:340:28: error: missing terminating " character
../netplay.cpp:428:24: warning: missing terminating " character
         S9xNPSetError ("The Snes9X NetPlay server implements a different\n\"
                        ^
../netplay.cpp:428:9: error: missing terminating " character
         S9xNPSetError ("The Snes9X NetPlay server implements a different\n\"
         ^
Makefile:2260: recipe for target '../snes9x_gtk-netplay.o' failed
make[3]: *** [../snes9x_gtk-netplay.o] Error 1
```

**Comment by vgturtle127** [comment]
What is the status of this? Hasn't the SNES9X core in libretro been around for awhile?

**Comment by Bracket-** [comment]
@sergiobenrocha2 Thanks for reporting. The error was introduced in 66b0f7e and is caused due to backslashes not being removed, causing double quotes being escaped.

Fixed in libretro PR [#17](https://github.com/libretro/snes9x/pull/17) which has been merged.

**Comment by sergiobenrocha2** [comment]
Is this "mergeable" yet?
